### ISSUE TITLE
[RELEASE] kes 2024-01-11T13-09-29Z

### ISSUE THREAD

**Issue by djwfyi** [minio/kes-docs#46]
kes release [2024-01-11T13-09-29Z](https://github.com/minio/kes/releases/tag/2024-01-11T13-09-29Z) has changes that impact the docs:

- [x] Reimplementation of Hashicorp Vault token renewal ([PR #428](https://github.com/minio/kes/pull/428))
- [x] Hashicorp Vault users can authenticate across namespaces ([PR #431](https://github.com/minio/kes/pull/431))

**Comment by feorlen** [comment]
These items have no docs impact or are already completed.

**Comment by djwfyi** [comment]
Done as part of PR #48
